/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class GetData extends javax.swing.JFrame {

    /**
     * Creates new form Dataandgeneratetable
     */
    public GetData() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        textId = new javax.swing.JTextField();
        textFirst = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Insertbut = new javax.swing.JButton();
        Updatebut = new javax.swing.JButton();
        Deletebut = new javax.swing.JButton();
        backbut = new javax.swing.JButton();
        nextbut = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 255, 51));

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel1.setText("Id:");

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel2.setText("First Name:");

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel3.setText("Sub 1:");

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel4.setText("Sub 2:");

        textId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textIdActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "First Name", "Sub 1", "Sub 2", "Sub 3", "Sub 4", "Sub 5"
            }
        ));
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable1.setFocusable(false);
        jTable1.setUpdateSelectionOnSort(false);
        jTable1.setVerifyInputWhenFocusTarget(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        Insertbut.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        Insertbut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/if_Add_27831 (1).png"))); // NOI18N
        Insertbut.setText("Insert");
        Insertbut.setToolTipText("");
        Insertbut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Insertbut.setFocusPainted(false);
        Insertbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertbutActionPerformed(evt);
            }
        });

        Updatebut.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        Updatebut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/if_Update_984748.png"))); // NOI18N
        Updatebut.setText("Update");
        Updatebut.setToolTipText("");
        Updatebut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Updatebut.setFocusPainted(false);
        Updatebut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdatebutActionPerformed(evt);
            }
        });

        Deletebut.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        Deletebut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/if_Remove_27874 (1).png"))); // NOI18N
        Deletebut.setText("Delete");
        Deletebut.setToolTipText("");
        Deletebut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Deletebut.setFocusPainted(false);
        Deletebut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeletebutActionPerformed(evt);
            }
        });

        backbut.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        backbut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/if_other-arrow-left-other-outline-stroke_763231.png"))); // NOI18N
        backbut.setText("Back");
        backbut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backbut.setFocusPainted(false);
        backbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbutActionPerformed(evt);
            }
        });

        nextbut.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        nextbut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/if_Arrow_Right_1063918.png"))); // NOI18N
        nextbut.setText("Next");
        nextbut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nextbut.setFocusPainted(false);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sub 1", "Sub 2", "Sub 3", "Sub 4", "Sub 5" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sub 1", "Sub 2", "Sub 3", "Sub 4", "Sub 5" }));
        jComboBox2.setSelectedIndex(1);
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textId, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                            .addComponent(textFirst, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Insertbut)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Updatebut)
                        .addGap(10, 10, 10)
                        .addComponent(Deletebut, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(backbut, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nextbut, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textFirst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(88, 88, 88)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Insertbut, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Updatebut, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Deletebut, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backbut, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nextbut, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(78, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void choosesub(String id, String first, String sub1, String sub2) {
        try {
            int i = Integer.parseInt(id);
            if (id.length() == 8 && !first.isEmpty()) {
                if (sub1.equals(sub2)) {
                    JOptionPane.showMessageDialog(null, "Choose 2 diffrent Subjects");
                } else if ((sub1.equals("Sub 1") && sub2.equals("Sub 2")) || (sub1.equals("Sub 2") && sub2.equals("Sub 1"))) {
                    m.addRow(new Object[]{i, textFirst.getText(), 1, 1, 0, 0, 0});
                } else if ((sub1.equals("Sub 1") && sub2.equals("Sub 3")) || (sub1.equals("Sub 3") && sub2.equals("Sub 1"))) {
                    m.addRow(new Object[]{i, textFirst.getText(), 1, 0, 1, 0, 0});
                } else if ((sub1.equals("Sub 1") && sub2.equals("Sub 4")) || (sub1.equals("Sub 4") && sub2.equals("Sub 1"))) {
                    m.addRow(new Object[]{i, textFirst.getText(), 1, 0, 0, 1, 0});
                } else if ((sub1.equals("Sub 1") && sub2.equals("Sub 5")) || (sub1.equals("Sub 5") && sub2.equals("Sub 1"))) {
                    m.addRow(new Object[]{i, textFirst.getText(), 1, 0, 0, 0, 1});
                } else if ((sub1.equals("Sub 2") && sub2.equals("Sub 3")) || (sub1.equals("Sub 3") && sub2.equals("Sub 2"))) {
                    m.addRow(new Object[]{i, textFirst.getText(), 0, 1, 1, 0, 0});
                } else if ((sub1.equals("Sub 2") && sub2.equals("Sub 4")) || (sub1.equals("Sub 4") && sub2.equals("Sub 2"))) {
                    m.addRow(new Object[]{i, textFirst.getText(), 0, 1, 0, 1, 0});
                } else if ((sub1.equals("Sub 2") && sub2.equals("Sub 5")) || (sub1.equals("Sub 5") && sub2.equals("Sub 2"))) {
                    m.addRow(new Object[]{i, textFirst.getText(), 0, 1, 0, 0, 1});
                } else if ((sub1.equals("Sub 3") && sub2.equals("Sub 4")) || (sub1.equals("Sub 4") && sub2.equals("Sub 3"))) {
                    m.addRow(new Object[]{i, textFirst.getText(), 0, 0, 1, 1, 0});
                } else if ((sub1.equals("Sub 3") && sub2.equals("Sub 5")) || (sub1.equals("Sub 5") && sub2.equals("Sub 3"))) {
                    m.addRow(new Object[]{i, textFirst.getText(), 0, 0, 1, 0, 1});
                } else if ((sub1.equals("Sub 4") && sub2.equals("Sub 5")) || (sub1.equals("Sub 5") && sub2.equals("Sub 4"))) {
                    m.addRow(new Object[]{i, textFirst.getText(), 0, 0, 0, 1, 1});
                }
                clearText();
                textId.requestFocus();

            } else if (id.length() != 8) {
                JOptionPane.showMessageDialog(null, "ID must be 8 numbers");
            } else if (first.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Enter First Name");
            }
        } catch (NumberFormatException | HeadlessException e) {
            JOptionPane.showMessageDialog(null, "Enter Invalid Format");
        }
    }
    private void backbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbutActionPerformed
        ChooseType c = new ChooseType();
        c.setVisible(true);
        c.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_backbutActionPerformed

    private void DeletebutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeletebutActionPerformed
        setTable();
        crow = jTable1.getSelectedRow();
        m.removeRow(crow);
    }//GEN-LAST:event_DeletebutActionPerformed

    private void UpdatebutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdatebutActionPerformed
        setTable();
        String sub1 = (String) jComboBox1.getSelectedItem();
        String sub2 = (String) jComboBox2.getSelectedItem();
        crow = jTable1.getSelectedRow();
        if (sub1 == sub2) {
            JOptionPane.showMessageDialog(null, "Choose 2 diffrent Subjects");
        } else if ((sub1.equals("Sub 1") && sub2.equals("Sub 2")) || (sub1.equals("Sub 2") && sub2.equals("Sub 1"))) {
            m.setValueAt(1, crow, 2);
            m.setValueAt(1, crow, 3);
            m.setValueAt(0, crow, 4);
            m.setValueAt(0, crow, 5);
            m.setValueAt(0, crow, 6);
        } else if ((sub1.equals("Sub 1") && sub2.equals("Sub 3")) || (sub1.equals("Sub 3") && sub2.equals("Sub 1"))) {
            m.setValueAt(1, crow, 2);
            m.setValueAt(0, crow, 3);
            m.setValueAt(1, crow, 4);
            m.setValueAt(0, crow, 5);
            m.setValueAt(0, crow, 6);
        } else if ((sub1.equals("Sub 1") && sub2.equals("Sub 4")) || (sub1.equals("Sub 4") && sub2.equals("Sub 1"))) {
            m.setValueAt(1, crow, 2);
            m.setValueAt(0, crow, 3);
            m.setValueAt(0, crow, 4);
            m.setValueAt(1, crow, 5);
            m.setValueAt(0, crow, 6);
        } else if ((sub1.equals("Sub 1") && sub2.equals("Sub 5")) || (sub1.equals("Sub 5") && sub2.equals("Sub 1"))) {
            m.setValueAt(1, crow, 2);
            m.setValueAt(0, crow, 3);
            m.setValueAt(0, crow, 4);
            m.setValueAt(0, crow, 5);
            m.setValueAt(1, crow, 6);
        } else if ((sub1.equals("Sub 2") && sub2.equals("Sub 3")) || (sub1.equals("Sub 3") && sub2.equals("Sub 2"))) {
            m.setValueAt(0, crow, 2);
            m.setValueAt(1, crow, 3);
            m.setValueAt(1, crow, 4);
            m.setValueAt(0, crow, 5);
            m.setValueAt(0, crow, 6);
        } else if ((sub1.equals("Sub 2") && sub2.equals("Sub 4")) || (sub1.equals("Sub 4") && sub2.equals("Sub 2"))) {
            m.setValueAt(0, crow, 2);
            m.setValueAt(1, crow, 3);
            m.setValueAt(0, crow, 4);
            m.setValueAt(1, crow, 5);
            m.setValueAt(0, crow, 6);
        } else if ((sub1.equals("Sub 2") && sub2.equals("Sub 5")) || (sub1.equals("Sub 5") && sub2.equals("Sub 2"))) {
            m.setValueAt(0, crow, 2);
            m.setValueAt(1, crow, 3);
            m.setValueAt(0, crow, 4);
            m.setValueAt(0, crow, 5);
            m.setValueAt(1, crow, 6);
        } else if ((sub1.equals("Sub 3") && sub2.equals("Sub 4")) || (sub1.equals("Sub 4") && sub2.equals("Sub 3"))) {
            m.setValueAt(0, crow, 2);
            m.setValueAt(0, crow, 3);
            m.setValueAt(1, crow, 4);
            m.setValueAt(1, crow, 5);
            m.setValueAt(0, crow, 6);
        } else if ((sub1.equals("Sub 3") && sub2.equals("Sub 5")) || (sub1.equals("Sub 5") && sub2.equals("Sub 3"))) {
            m.setValueAt(0, crow, 2);
            m.setValueAt(0, crow, 3);
            m.setValueAt(1, crow, 4);
            m.setValueAt(0, crow, 5);
            m.setValueAt(1, crow, 6);
        } else if ((sub1.equals("Sub 4") && sub2.equals("Sub 5")) || (sub1.equals("Sub 5") && sub2.equals("Sub 4"))) {
            m.setValueAt(0, crow, 2);
            m.setValueAt(0, crow, 3);
            m.setValueAt(0, crow, 4);
            m.setValueAt(1, crow, 5);
            m.setValueAt(1, crow, 6);
        }
        m.setValueAt(textId.getText(), crow, 0);
        m.setValueAt(textFirst.getText(), crow, 1);
        clearText();
    }//GEN-LAST:event_UpdatebutActionPerformed

    private void InsertbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertbutActionPerformed
        setTable();
        String id = textId.getText();
        String first = textFirst.getText();
        String sub1 = (String) jComboBox1.getSelectedItem();
        String sub2 = (String) jComboBox2.getSelectedItem();
        choosesub(id, first, sub1, sub2);
    }//GEN-LAST:event_InsertbutActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        try {
            int row = jTable1.getSelectedRow();

            String s1 = jTable1.getValueAt(row, 0).toString();
            String s2 = jTable1.getValueAt(row, 1).toString();
            String s3 = jTable1.getValueAt(row, 2).toString();
            String s4 = jTable1.getValueAt(row, 3).toString();
            String s5 = jTable1.getValueAt(row, 4).toString();
            String s6 = jTable1.getValueAt(row, 5).toString();
            String s7 = jTable1.getValueAt(row, 6).toString();

        } catch (Exception e) {
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void textIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textIdActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed
    DefaultTableModel m;
    int crow;

    private void setTable() {
        m = (DefaultTableModel) jTable1.getModel();
    }

    private void clearText() {
        textId.setText("");
        textFirst.setText("");
        jComboBox1.setSelectedIndex(0);
        jComboBox2.setSelectedIndex(1);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GetData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GetData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GetData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GetData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GetData().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Deletebut;
    private javax.swing.JButton Insertbut;
    private javax.swing.JButton Updatebut;
    private javax.swing.JButton backbut;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton nextbut;
    private javax.swing.JTextField textFirst;
    private javax.swing.JTextField textId;
    // End of variables declaration//GEN-END:variables
}
